name: publish package to test-pypi

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Configure private repository
        run: |
          poetry config repositories.test https://test.pypi.org/legacy/
      - name: Build and publish
        run: |
          poetry config pypi-token.test ${{ secrets.TEST_PYPI_TOKEN }}
          poetry publish --build --no-interaction --repository test
